sonar.projectKey=exalt_classement
sonar.projectName=exalt_classement
sonar.sources=.
sonar.exclusions=coverage/**,tests/**,node_modules/**,.gitlab-ci.yml
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
